---
name: Static Checks - Go

on:
  push:
    branches:
      - main
    paths:
      - '**/go.*'
      - '**.go'
  pull_request:
    paths:
      - '**/go.*'
      - '**.go'

concurrency:
  group: static-checks-go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-go-module:
    name: ${{ matrix.modDir }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modDir:
          - using-interfaces/example
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Test
        run: go test ${{ matrix.modDir }}/...

      - name: Vet
        run: go vet ${{ matrix.modDir }}/...

      - name: Staticcheck
        run: |-
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck -go 1.22 ${{ matrix.modDir }}/...
